site_name: Turtle Brand Protection
site_description: Documentação interna de tecnologias e sistemas da Turtle
repo_url: https://github.com/Turtle-BP
repo_name: Turtle-BP

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search:
      lang: pt

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - tables

nav:
  - Home: index.md
  - API: API.md
  - Scrapers:
      - O que é um Scraper?: Scrapers/O_que_e_um_scraper.md
      - Pipeline do Scraper: Scrapers/pipeline_Scraper.md
      - Como iniciar um Scraper?: Scrapers/como_iniciar_o_scraper.md
